### ISSUE TITLE
Noise in record playback

### ISSUE THREAD

**Issue by KonradIT** [googlesamples/android-WearSpeakerSample#1]
There is a lot of noise in the playback of the recorded voice note. Happens on the Huawei Watch as well.

**Comment by codingjeremy** [comment]
I am guessing this is just because your in a loud area? I tried with a Huawei watch and several others in an office with a good amount of noise, and it wasn't bad for me. Maybe try again in a quiet area and see if you have the same problem. If you do, it might be hardware related since I have the same watch.
